CREATE TABLE IF NOT EXISTS rg90_secuencias (
    clave VARCHAR(120) NOT NULL,
    siguiente_lote INT NOT NULL DEFAULT 1,
    PRIMARY KEY (clave)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
